## Resolução de Problemas por meio de Busca Não-Informada



In [1]:
import numpy as np
from collections import deque

linhas = 5
colunas = 3

matriz_estados = np.zeros((linhas,colunas), dtype=np.int32)
matriz_estados[0:linhas, 0:colunas] = 1

custo_caminho = 1

print (matriz_estados)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


#### esquerda, direita, cima, baixo, limpar

In [2]:
acoes = [1,1,1,1,1]

In [3]:
def estado(linha, coluna):
    erro = True
    
    estado_inicial = [linha,coluna]

    if estado_inicial[0] > linhas or estado_inicial[1] > colunas:
        erro = False
    
    return erro

In [4]:
def acoes_possiveis(estado, matriz_transicao):
    acoes = [1,1,1,1,1]
    
    if estado[0] == 0:
        acoes[0] = 0
        
    elif estado[0] == (linhas-1):
        acoes[1] = 0
    
    if estado[1] == 0:
        acoes[2] = 0
    
    elif estado[1] == (colunas-1):
        acoes[3] = 0
       
    if matriz_transicao[estado[0]][estado[1]] == 0:
        acoes[4] = 0
        
    return acoes

In [5]:
def testar_objetivo(matriz_transicao):
    teste_objetivo = True
    for linhas in matriz_transicao:
        for valor in linhas:
            if valor == 1:
                teste_objetivo = False
      
    return teste_objetivo
            

In [6]:
class No:

    def __init__(self, estado, pai, acao, custo, matriz_transicao):
        self.estado = estado
        self.pai = pai
        self.acao = acao
        self.custo = custo
        self.matriz_transicao = matriz_transicao
        
    def __repr__(self):
        if self.pai:
            return 'No{\n Estado: %s\n Pai: %s,\n Ação: %s,\n Custo: %s,\n Matriz Atual:\n %s\n}' % (self.estado, self.pai.estado, self.acao, self.custo, self.matriz_transicao)
        else:
            return 'No{\n Estado: %s,\n Pai: %s,\n Ação: %s,\n Custo: %s,\n Matriz Atual:\n %s\n}' % (self.estado, 'None', self.acao, self.custo, self.matriz_transicao)

In [7]:
def no_filho(pai, acao, matriz_transicao):
    
    estado_atual = pai.estado.copy()
    
    if acao[0] == 1:
        estado_atual[0] -= 1
        acao_atual = "Esquerda"
        
    elif acao[1] == 1:
        estado_atual[0] += 1
        acao_atual = "Direita"
        
    elif acao[2] == 1:
        estado_atual[1] -= 1
        acao_atual = "Cima"
    
    elif acao[3] == 1:
        estado_atual[1] += 1
        acao_atual = "Baixo"
    
    elif acao[4] == 1:        
        matriz_transicao[pai.estado[0]][pai.estado[1]] = 0
        acao_atual = "Limpar"
        
    # print('pai.estado: %s acao: %s [%s] estado: %s custo %s' %(pai.estado, acao, acao_atual, estado_atual, pai.custo+1))
    
    no = No(estado_atual, pai, acao_atual, pai.custo + 1, matriz_transicao)
    
    return no

In [8]:
""" Definição do Nó Raiz """

linha = 2
coluna = 2

if estado(linha,coluna):
    
    estado_inicial = [linha-1, coluna-1]
    no_inicial = No(estado_inicial, None, None, 0, matriz_estados)
    
    print(no_inicial)
    
else:
    print("Erro")

No{
 Estado: [1, 1],
 Pai: None,
 Ação: None,
 Custo: 0,
 Matriz Atual:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
}


In [9]:
def avaliar_solucao(no_final):
    vetor_solucao = [no_final.acao]

    while not no_final.pai == None:
        vetor_solucao.append(no_final.acao)
        no_final = no_final.pai
        
    print (vetor_solucao)

In [10]:
""" Busca em largura """

no = no_inicial

borda = deque([no])
explorado = deque()
limite=0

while limite < 500:
    
    limite+=1
    
    if limite == 500:
        print(no)
    
    
    if testar_objetivo(no.matriz_transicao):
        matriz_final = no.matriz_transicao
        avaliar_solucao(borda.popleft())
        break
        
    elif len(borda) == 0: 
        print('Falha ao explorar os nós')
        break
        
    else:
        
        no = borda.popleft()
        
        explorado.append(no.matriz_transicao)
    
        acoes = acoes_possiveis(no.estado, no.matriz_transicao)
        
        for i, valor in enumerate(acoes):
            acao_atual = [0,0,0,0,0]
            if valor == 1:
                acao_atual[i] = 1
                filho = no_filho(no, acao_atual, no.matriz_transicao.copy())  
                if len(list(filter(lambda x: x.estado == filho.estado, borda))) == 0:                    
                    borda.append(filho)    

print("\n\n", matriz_final)

['Direita', 'Direita', 'Direita', 'Limpar', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Direita', 'Direita', 'Direita', 'Direita', 'Limpar', 'Cima', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Direita', 'Direita', 'Direita', 'Direita', 'Limpar', 'Baixo', 'Baixo', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Esquerda', 'Limpar', 'Direita', 'Direita', 'Direita', 'Direita', 'Limpar', 'Cima', 'Esquerda']


 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [11]:
def bpl_recursiva(no_atual, limite):
    if testar_objetivo(no_atual.matriz_transicao):
        avaliar_solucao(no_atual)
        return('OK')
        
    elif limite == 0:
        return "erro"
    
    else:
        corte = False        
        acoes = acoes_possiveis(no_atual.estado, no_atual.matriz_transicao)
        
        if acoes == [0,0,0,0,0]:
            return "erro"

        else:
            for i, valor in enumerate(acoes):
                acao_atual = [0,0,0,0,0]

                if valor == 1:
                    acao_atual[i] = 1
                    filho = no_filho(no_atual, acao_atual, no_atual.matriz_transicao.copy())                
                    resultado = bpl_recursiva(filho, limite-1)

                    if(resultado == "erro"):
                        corte = True

                    else: 
                        return resultado
        
        if corte:        
            return "erro"

In [ ]:
no_inicial = None

""" Definição do Nó Raiz """

linha = 2
coluna = 2

limite = 50

if estado(linha,coluna):
    estado_inicial = [linha-1, coluna-1]
    no_inicial = No(estado_inicial, None, None, 0, matriz_estados)
    
else:
    print("Erro")


print(bpl_recursiva(no_inicial, limite))